M3 l1 spring
otuskotlin/202206-ok-marketplace pull request #10
Opened 2022-08-13 18:47 UTC by evgnep

2022-08-14 05:41 UTC, svok requested changes

2022-08-14 05:41 UTC, svok commented on m3l1-spring/src/main/kotlin/ru/otuskotlin/m3l1/spring/controller/UserController.kt
> +
У тебя не будет времени на то, чтобы учить студентов спринго-лапше. На каждом занятии происходит овертайм, каждый раз не хватает времени на то, чтоб рассказать как делать маркетплейс, а тут появляется какое-то левое приложение, которое вообще ничем не помогает в разработке маркетплейса, но при этом демонстрирует самые худшие практики на рынке разработки.
Я против того,  чтобы студенты учились худшим ошибкам на рынке.
Гадостям они без нас научатся.

Не вижу никакого смысла в модуле m3l1-spring.
Сэкономь время и лучше расскажи им как делаются интеграционные тесты на спринге.

2022-08-14 05:41 UTC, svok commented on ok-marketplace-app-spring/Dockerfile
> +COPY build/libs/ok-marketplace-app-spring-0.0.1-SNAPSHOT.jar /app/app.jar
Зачем это? В спринге есть уже готовый bootBuildImage. Чем он тебя не устраивает?

2022-08-14 05:41 UTC, svok commented on ok-marketplace-app-spring/src/main/kotlin/ru/otus/otuskotlin/markeplace/springapp/api/controllerUtils.kt
> +                                 toTransport: MkplContext.() -> RESP): RESP =
1. И вместо одной DSL-лямбды у тебя получилась тяжеловесная функция со 100500 аргументами.
В чем профит? Не принято так работать с DSL. Есть возможности инлай-функций, генериков и пр. 
2. Мы вообще на этом занятии еще до этого не доходим. **На этом занятии цель одна - сделать минимальное приложение БЕЗ ЛОГИКИ, которое умеет отдавать ТОЛЬКО СТАБЫ. Т.е. только фиксированные ответы.**
3. В общем, эта функция пока не нужна. Мы потом будет отдельно добавлять. И в эту функцию потом пойдет обработка ошибок, логирование, аутентификация и пр. Но не в таком виде. Сделай как в прошлый раз.

2022-08-14 05:41 UTC, svok commented on ok-marketplace-app-spring/src/main/kotlin/ru/otus/otuskotlin/markeplace/springapp/api/v1/contextExtensions.kt
> +
Здесь все лишнее. Еще раз, на этом занятии только стабы. Логика не должна появиться в этом занятии. Обработка ошибок не нужна. Только запутаешь студентов.

Стабы только для того, чтоб максимально быстро предоставить возможность смежным командам начать интеграцию с нашим АПИ.

2022-08-14 05:41 UTC, svok commented on ok-marketplace-app-spring/src/main/kotlin/ru/otus/otuskotlin/markeplace/springapp/api/v1/service/AdService.kt
> +            MkplWorkMode.PROD -> TODO()
Никакой логики на этом занятии не должно быть.
Никаких PROD, TEST обрабатывать не нужно.
Запрос должен возвращать только стаб и больше ничего не делать

2022-08-14 05:41 UTC, svok commented on ok-marketplace-app-spring/src/main/kotlin/ru/otus/otuskotlin/markeplace/springapp/api/v1/service/AdService.kt
> +class AdService {
В этом виде нам этот файл вообще не понадобится.
Мы делали реализацию логики в двух видах.
1.
```kotlin
@Controller
class Controller(service) {
    fun postHandler1(api1: ApiModel): ApiResponse1 = service.requestHandler1(api1)
}
@Service
class Service {
    fun requestHandler1(api1): ApiResponse1 {
       создаем контекст, заполняем, обрабатываем ошибки
       вызов бизнес логики или возврат стаба
    }
}
```
2. Все, что в сервисе, уходит в обертку с одной лямбдой. Бизнес логика находится в отдельном модуле и используется во всех фреймворках. Сервис как таковой просто не нужен.
```kotlin
class Controller(bizLogic) {
    fun postHandler1(api1: ApiModel): ApiResponse1 = requestHandler(COMMAND1) { this: Context -> 
        bizLogic.exec(this)
    }
}
```

Скорее всего, у нас будет вариант 2.

2022-08-14 05:41 UTC, svok commented on ok-marketplace-app-spring/src/main/kotlin/ru/otus/otuskotlin/markeplace/springapp/api/v2/contextExtensions.kt
> +fun MkplContext.errorResponse(error: (MkplError) -> MkplError) =
В этом файле расширения контекста. Я уже написал, что он не нужен, но почему он продублирован?

2022-08-14 05:41 UTC, svok commented on ok-marketplace-app-spring/src/main/kotlin/ru/otus/otuskotlin/markeplace/springapp/api/v2/service/AdServiceV2.kt
> +                adResponse = Bolt.getModel().apply { id = requestedId }
Болтов на этом потоке не будет. Смотри транспортные модели. Возвращаем только `productId`

2022-08-14 05:41 UTC, svok commented on ok-marketplace-app-spring/src/main/kotlin/ru/otus/otuskotlin/markeplace/springapp/api/v2/service/AdServiceV2.kt
> +class AdServiceV2 {
Как я уже написал, такой сервис вообще не нужен.
И уж тем более его не нужно копипастить

2022-08-14 05:41 UTC, svok commented on ok-marketplace-app-spring/src/test/kotlin/ru/otus/otuskotlin/markeplace/springapp/ApplicationTests.kt
> +    }
А вот тест нужно сделать в первую очередь. На прошлом потоке мне пришлось за Дмитрия оправдываться почему тестов нет. Потом мне самому пришлось добавлять тесты.

2022-08-14 05:41 UTC, svok commented on settings.gradle.kts
> +        kotlin("plugin.jpa") version pluginJpa apply false
зачем тебе жпа? Ее вообще на курсе не будет

2022-08-14 05:41 UTC, svok commented on ok-marketplace-app-spring/build.gradle.kts
> +    implementation("org.springdoc:springdoc-openapi-ui:$springdocOpenapiUiVersion")
Именно в таком виде я и НЕ рекомендовал использовать студентам OpenAPI.
Вот так мы используем просто тот файл спеки, из которого сгенерированы все модели.

![image](https://user-images.githubusercontent.com/12605904/184523914-910dfdde-75af-4586-abe5-999bc358e194.png)
![image](https://user-images.githubusercontent.com/12605904/184523942-8a2a364e-77f7-41bf-ae83-12f13925c743.png)
![image](https://user-images.githubusercontent.com/12605904/184523958-5b10dbc4-5237-4eae-9ab0-19e6591b96cd.png)

2022-08-14 05:41 UTC, svok commented on ok-marketplace-app-spring/src/main/kotlin/ru/otus/otuskotlin/markeplace/springapp/api/v1/service/AdService.kt
> +import marketplace.stubs.Bolt
Мне не понятно откуда появился болт. У тебя в ПР его нет, в текущей версии проекта его тоже нет.

В любом случае, тебе необходимо сделать модуль стабов. И мне нужен стаб вот такого вида
https://github.com/otuskotlin/202202-ok-marketplace/blob/main/ok-marketplace-stubs/src/commonMain/kotlin/ru/otus/otuskotlin/marketplace/stubs/MkplAdStub.kt

2022-08-14 05:53 UTC, evgnep commented on m3l1-spring/src/main/kotlin/ru/otuskotlin/m3l1/spring/controller/UserController.kt
> +
я использую это для иллюстрации некоторых слайдов. Если не буду укладываться в тайминг - уберу

2022-08-14 05:53 UTC, evgnep commented on ok-marketplace-app-spring/Dockerfile
> +COPY build/libs/ok-marketplace-app-spring-0.0.1-SNAPSHOT.jar /app/app.jar
демонстрировать докер лучше на докере, а не на обертке в виде грейдла

2022-08-14 05:58 UTC, evgnep commented on ok-marketplace-app-spring/src/main/kotlin/ru/otus/otuskotlin/markeplace/springapp/api/controllerUtils.kt
> +                                 toTransport: MkplContext.() -> RESP): RESP =
я увидел копипасту и убрал ее. Когда проект разовьется - ничто не мешает это выкинуть

2022-08-14 06:06 UTC, evgnep commented on settings.gradle.kts
> +        kotlin("plugin.jpa") version pluginJpa apply false
для демо

2022-08-14 06:09 UTC, evgnep commented on ok-marketplace-app-spring/src/main/kotlin/ru/otus/otuskotlin/markeplace/springapp/api/v1/service/AdService.kt
> +import marketplace.stubs.Bolt
в пр он есть, иначе бы код не собирался.

Окей, переделаю на твой

2022-08-14 15:55 UTC, evgnep commented on ok-marketplace-app-spring/src/main/kotlin/ru/otus/otuskotlin/markeplace/springapp/api/controllerUtils.kt
> +                                 toTransport: MkplContext.() -> RESP): RESP =
Но с учетом отсутствия сервисов - функция не нужна, выкинул

2022-08-14 15:56 UTC, evgnep commented on ok-marketplace-app-spring/src/main/kotlin/ru/otus/otuskotlin/markeplace/springapp/api/v1/service/AdService.kt
> +import marketplace.stubs.Bolt
не, ты прав - я его забыл добавить в реп. Переделал на твой

2022-08-14 16:56 UTC, evgnep commented on ok-marketplace-app-spring/build.gradle.kts
> +    implementation("org.springdoc:springdoc-openapi-ui:$springdocOpenapiUiVersion")
сделал

2022-08-14 17:15 UTC, evgnep commented on ok-marketplace-app-spring/src/test/kotlin/ru/otus/otuskotlin/markeplace/springapp/ApplicationTests.kt
> +    }
сделал

2022-08-14 17:15 UTC, evgnep commented on ok-marketplace-app-spring/src/main/kotlin/ru/otus/otuskotlin/markeplace/springapp/api/v1/contextExtensions.kt
> +
взял из прошлого занятия. Выкинул

2022-08-15 04:57 UTC, svok approved these changes

2022-08-22 05:57 UTC, merged